# integrations/github_integration.py
import os
import datetime
from dotenv import load_dotenv

load_dotenv()


def get_secret(key):
    try:
        import streamlit as st
        v = st.secrets.get(key)
        if v:
            return v
    except Exception:
        pass
    return os.getenv(key)


class GitHubIntegration:
    def __init__(self):
        from github import Github
        token = get_secret("GITHUB_TOKEN")
        self.gh = Github(token)
        self._user = None

    def _get_user(self):
        if not self._user:
            self._user = self.gh.get_user()
        return self._user

    def get_repo(self, repo_name):
        try:
            return self.gh.get_repo(repo_name)
        except Exception:
            return None

    def repo_exists(self, repo_name):
        return self.get_repo(repo_name) is not None

    def create_repo(self, repo_name, description="", private=False):
        """
        Create a new public repo for a use case.
        Initialises with README, .gitignore and base folder structure.
        Returns (repo, success, message).
        """
        try:
            user = self._get_user()
            name = repo_name.split("/")[-1]

            repo = user.create_repo(
                name=name,
                description=description or "Generated by ARIA Agent",
                private=private,
                auto_init=True,
                gitignore_template="Python"
            )

            # Add base folder structure
            for folder in ["src/.gitkeep", "tests/.gitkeep", "docs/.gitkeep"]:
                try:
                    repo.create_file(
                        folder,
                        f"ARIA: initialise {folder.split('/')[0]}/ folder",
                        ""
                    )
                except Exception:
                    pass

            return repo, True, f"Repo created: {repo.html_url}"
        except Exception as e:
            return None, False, f"Could not create repo: {e}"

    def create_webhook(self, repo_name, webhook_url, secret):
        """
        Automatically create a PR webhook on the target repo.
        Called immediately after repo creation — no manual GitHub steps needed.
        Returns (success, message).
        """
        try:
            repo = self.gh.get_repo(repo_name)
            if not repo:
                return False, f"Repo not found: {repo_name}"

            # Check if webhook already exists to avoid duplicates
            existing = repo.get_hooks()
            for hook in existing:
                if hook.config.get("url","") == webhook_url:
                    return True, "Webhook already exists"

            repo.create_hook(
                name="web",
                config={
                    "url": webhook_url,
                    "content_type": "json",
                    "secret": secret,
                    "insecure_ssl": "0"
                },
                events=["pull_request"],
                active=True
            )
            return True, f"Webhook created on {repo_name}"
        except Exception as e:
            return False, f"Webhook creation failed: {e}"

    def setup_repo_with_webhook(self, repo_name, description=""):
        """
        One-shot method: creates repo + configures webhook automatically.
        Called from the Use Cases tab when user creates a new use case.
        Returns dict with repo_url, webhook_ok, messages.
        """
        result = {
            "repo_url": None,
            "repo_ok": False,
            "webhook_ok": False,
            "messages": []
        }

        # Step 1 — create repo
        repo, repo_ok, repo_msg = self.create_repo(repo_name, description)
        result["repo_ok"] = repo_ok
        result["messages"].append(repo_msg)

        if not repo_ok:
            return result

        result["repo_url"] = repo.html_url

        # Step 2 — create webhook automatically
        webhook_url = get_secret("RAILWAY_WEBHOOK_URL")
        secret      = get_secret("GITHUB_WEBHOOK_SECRET")

        if not webhook_url:
            result["messages"].append(
                "Warning: RAILWAY_WEBHOOK_URL not set — webhook skipped. "
                "Add it to your secrets to enable automatic Kanban updates."
            )
            return result

        webhook_url = webhook_url.rstrip("/") + "/webhook/github"
        wh_ok, wh_msg = self.create_webhook(repo_name, webhook_url, secret or "")
        result["webhook_ok"] = wh_ok
        result["messages"].append(wh_msg)

        return result

    def create_pr(self, repo_name, title, code, filename,
                  description, mode="DEVELOPER"):
        """
        Full PR workflow for a USE CASE repo — never touches ARIA repo.
        Returns (pr_url, success, message).
        """
        try:
            repo = self.gh.get_repo(repo_name)
            if not repo:
                return None, False, f"Repo not found: {repo_name}"

            timestamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
            branch_name = f"aria/{mode.lower()}-{timestamp}"
            base = repo.get_branch("main")

            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base.commit.sha
            )

            try:
                existing = repo.get_contents(filename, ref=branch_name)
                repo.update_file(
                    path=filename,
                    message=f"[ARIA] {title}",
                    content=code,
                    sha=existing.sha,
                    branch=branch_name
                )
            except Exception:
                repo.create_file(
                    path=filename,
                    message=f"[ARIA] {title}",
                    content=code,
                    branch=branch_name
                )

            pr = repo.create_pull(
                title=f"[ARIA] {title}",
                body=self._pr_body(description, mode),
                head=branch_name,
                base="main"
            )
            return pr.html_url, True, f"PR created: {pr.html_url}"

        except Exception as e:
            return None, False, f"PR creation failed: {e}"

    def _pr_body(self, description, mode):
        return f"""## ARIA Generated — {mode} Mode

{description}

---
### Review checklist
- [ ] Code logic is correct
- [ ] No hardcoded secrets
- [ ] Error handling in place
- [ ] Tests included and passing

---
*Generated by ARIA Agent — review before merging*
"""

    def get_pr_status(self, repo_name, pr_number):
        try:
            repo = self.gh.get_repo(repo_name)
            pr = repo.get_pull(pr_number)
            return {
                "state": pr.state,
                "merged": pr.merged,
                "url": pr.html_url,
                "title": pr.title
            }
        except Exception as e:
            return {"error": str(e)}

    def get_open_prs(self, repo_name):
        try:
            repo = self.gh.get_repo(repo_name)
            return [
                {"number": pr.number, "title": pr.title, "url": pr.html_url}
                for pr in repo.get_pulls(state="open")
            ]
        except Exception:
            return []